/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package _crwaling;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    @Test 
    void testYgosu() {
        
        App test = new App();
        test.ygosu("https://ygosu.com/community/stock");
        // classUnderTest.ygosu("https://ygosu.com/community/stock");
        // assertNotNull(classUnderTest.getGreeting(), "app should have a greeting");
    }

    @Test
    void testNaver(){
        App test = new App();
        test.naver("https://news.naver.com/main/main.naver?mode=LSD&mid=shm&sid1=101");
    }
}
