/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package _crwaling;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    @Test 
    void testYgosu() {
        App classUnderTest = new App();
        classUnderTest.ygosu();
        // assertNotNull(classUnderTest.getGreeting(), "app should have a greeting");
    }

    @Test
    void testNaver(){
        App test = new App();
        test.naver();
    }
}
